Adding mac dependency on xcode

diff --git a/bin/install_dependencies b/bin/install_dependencies
--- a/bin/install_dependencies
+++ b/bin/install_dependencies
@@ -18,13 +18,14 @@ case "$os_env" in
     "linux")
         echo "Dependencies installed via container (skipping)"
         ;;
-    # Temporarily disabling as it was causing build to fail for unknown reasons
-    #"mac")
-    #    echo "Installing mac (darwin) dependencies ..."
-    #    set -x
-    #    brew install ccache
-    #    set +x
-    #    ;;
+    "mac")
+        echo "Installing mac (darwin) dependencies ..."
+        set -x
+        xcode-select --install || true
+        # Temporarily disabling as it was causing build to fail for unknown reasons
+        #brew install ccache
+        set +x
+        ;;
     *)
         echo "No dependencies to install for '$os_env'"
         ;;
